version: "3.7"

services:
  postgres:
    image: timescale/timescaledb:latest-pg12
    restart: always
    ports:
      - ${PG_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}

  graphql-engine:
    image: hasura/graphql-engine:v1.2.2.cli-migrations-v2
    ports:
      - ${HASURA_GRAPHQL_PORT}:8080
    depends_on:
      - "postgres"
    volumes:
      - "${HASURA_GRAPHQL_METADATA_DIRECTORY}:/hasura-metadata"
      - "${HASURA_GRAPHQL_MIGRATIONS_DIRECTORY}:/hasura-migrations"
    restart: always
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_CORS_DOMAIN: "*"
      HASURA_GRAPHQL_DATABASE_URL: postgres://${PG_USERNAME}:${PG_PASSWORD}@postgres/${PG_DATABASE}
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "${JWT_SECRET}" }'

volumes:
  db_data:
